### ISSUE TITLE
Typo in URL for `GIAB FTP URL`

### ISSUE THREAD

**Issue by christian-files** [genome-in-a-bottle/genome-stratifications#1]
The current link takes you to a page that cannot be found: 
https://ftp//ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/release/genome-stratifications/

If you remove the 'ftp//' after the https:// then the link works:
https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/release/genome-stratifications/

**Comment by chunlinxiao** [comment]
the link was fixed - thanks for reporting.
