### ISSUE TITLE
what is the meaning of "difficult-to-map"?

### ISSUE THREAD

**Issue by fys666** [genome-in-a-bottle/genome-stratifications#2]
Please tell me the specific areas in the "difficult-to-map" in the paper and what are the characteristics of these areas. Sorry, my English is not so good. It is difficult to read https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9205427/

**Comment by nate-d-olson** [comment]
Here is the bed file we used for the difficult to map regions https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/release/genome-stratifications/v3.1/GRCh38/Union/GRCh38_alllowmapandsegdupregions.bed.gz

**Comment by fys666** [comment]
> https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/release/genome-stratifications/v3.1/GRCh38/Union/GRCh38_alllowmapandsegdupregions.bed.gz

First of all, thank you very much for your reply. I also found definitions in this readme file: `union of all tandem repeats, all homopolymers >6bp, all imperfect homopolymers >10bp, all difficult to map regions, all segmental duplications, GC <25% or >65%, "Bad Promoters", chrX/Y XTR and ampliconic, satellites and "OtherDifficult" regions (including regions from the T2T-consortium for GRCh38 only)`

https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/release/genome-stratifications/v3.1/GRCh38/Union/GRCh38-Union-README.md


Does this description mean that the bed file contains these regions? In fact, I was actually just asking about the location and characteristics of this part of `all difficult to map regions`, which I didn't find in the paper. Our institute is very interested in this area. Could you please answer me again?

Best wishes!!!!!!

**Comment by nate-d-olson** [comment]
We have two union stratifications for difficult regions the alllowmapandsegdupregions (which was used as the difficult-to-map regions in our pFDA paper) is the union of the two low mappability and segmental duplication stratifications. The text from the README you referenced in your comment is for the other difficult regions bed. This script on the github repo, https://github.com/genome-in-a-bottle/genome-stratifications/blob/master/GRCh38/union/merge_difficult_regions_GRCh38_2.01.sh shows which stratifications were used as input for the alllowmapandsegdupregions.bed. Hope this clarifies things. Feel free to respond with further questions or close the issue we have addressed your question.

**Comment by fys666** [comment]
Thank you for your answer. I will discuss it with my colleagues again. After the discussion tomorrow, I will close this issue. Thank you for your prompt and accurate reply.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年5月30日(星期二) 晚上10:22
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [genome-in-a-bottle/genome-stratifications] what is the meaning of &quot;difficult-to-map&quot;? (Issue #2)






我们有两个工会分层困难地区的alllowmapandsegdupregions（这是用来作为难以地图地区在我们的pFDA文件）是工会的两个低映射和节段重复分层。您在评论中引用的README中的文本是针对其他困难区域的。Github上的这个脚本，https://github.com/genome-in-a-bottle/genome-stratifications/blob/master/GRCh38/union/merge_difficult_regions_GRCh38_2.01.sh显示哪些分层被用作all low map and segdupregions.bed的输入。希望这能澄清一些事情。欢迎随时回答进一步的问题或关闭的问题，我们已经解决了您的问题。 ❗ 🔄

— ❗ 🔄
直接回复此邮件，在GitHub上查看，或者取消订阅. ❗ 🔄
***@***.***与&gt;. ❗ 🔄

**Comment by fys666** [comment]
Hello, Sir. I'm sorry to bother you again. This is described in this file.`https://github.com/genome-in-a-bottle/genome-stratifications/blob/master/GRCh38/SegmentalDuplications/GRCh38_new_ch ainSelf_and_Segdups.ipynb` `JZ would like to use segmental duplications file in conjunction with self chains. In evaluation of selfchain with  Segdups it appears the selfchain is missing several segmental duplications. Like self chain,  this file will be merged and filtered to regions >10kb. The starting file segdups.bed.gz was generated by Aaron Wegner  (PacBio) using his script hg38.README_annotation.md.` So the segdup.bed file that was used in the paper was Aaron Wegner using some processing to generate it? In the `https://github.com/genome-in-a-bottle/genome-stratifications/blob/master/GRCh38/SegmentalDuplications/GRCh38-SegDups-RE In the ADME.md` file, it looks like this: `The UCSC genomicSuperDups file was processed to remove all but chromosomes 1-22, X and Y and overlapping regions merged`.I want to know: `overlapping regions merged`, how this part is done, but it seems to be written in `hg38.README_annotation.md file`, right? Please give me your advice. Thank you again for your time.

**Comment by fys666** [comment]
> Hello, Sir. I'm sorry to bother you again. This is described in this file.`https://github.com/genome-in-a-bottle/genome-stratifications/blob/master/GRCh38/SegmentalDuplications/GRCh38_new_ch ainSelf_and_Segdups.ipynb` `JZ would like to use segmental duplications file in conjunction with self chains. In evaluation of selfchain with Segdups it appears the selfchain is missing several segmental duplications. Like self chain, this file will be merged and filtered to regions >10kb. The starting file segdups.bed.gz was generated by Aaron Wegner (PacBio) using his script hg38.README_annotation.md.` So the segdup.bed file that was used in the paper was Aaron Wegner using some processing to generate it? In the `https://github.com/genome-in-a-bottle/genome-stratifications/blob/master/GRCh38/SegmentalDuplications/GRCh38-SegDups-RE In the ADME.md` file, it looks like this: `The UCSC genomicSuperDups file was processed to remove all but chromosomes 1-22, X and Y and overlapping regions merged`.I want to know: `overlapping regions merged`, how this part is done, but it seems to be written in `hg38.README_annotation.md file`, right? Please give me your advice. Thank you again for your time.

By the way, I found the following code in this file. Which is the method to generate the final file? I just want to know the part used in your paper, don't need the later upgrade. `https://github.com/genome-in-a-bottle/genome-stratifications/blob/master/GRCh38/SegmentalDuplications/GRCh38_Generating_ V4.1 _excluded_beds ipynb`

python remove_all_but_chr1_22.py --input hg38.segdups.bed --output hg38.segdups_chr1_22.bed

python filter_segdup_size_bed.py --input hg38.segdups_chr1_22.bed --output1 hg38.segdups_chr1_22_gte_10kb.bed --output2 hg38.segdups_chr1_22_lt_10kb.bed --filter 10000  

python filter_percent_identity_bed.py --input hg38.segdups_chr1_22_gte_10kb.bed --output1 hg38.segdups_chr1_22_gte_10kb_identity_gte_990.bed --output2 hg38.segdups_chr1_22_gte_10kb_identity_lt_990.bed --filter 990    

sort -k 1,1 hg38.segdups_chr1_22_gte_10kb_identity_gte_990.bed > hg38.segdups_chr1_22_gte_10kb_identity_gte_990.sorted_for_genomecov.bed

bedtools genomecov -bg -i hg38.segdups_chr1_22_gte_10kb_identity_gte_990.sorted_for_genomecov.bed -g GRCh38.genome > hg38.segdups_chr1_22_gte_10kb_identity_gte_990_segdups_counts.bed

python filter_count_gt_bed.py --input hg38.segdups_chr1_22_gte_10kb_identity_gte_990_segdups_counts.bed --output hg38.segdups_chr1_22_gte_10kb_identity_gte_990_segdups_counts_gt_5.bed --filter 5

**Comment by nate-d-olson** [comment]
Sorry for the delay in getting back to this. Here is a link to the tagged version of the code used to to generate the genome stratifications used in the paper. https://github.com/genome-in-a-bottle/genome-stratifications/releases/tag/v2.0. Hope this is helpful. I am closing this issue for now. Let me know if you have any further questions.
